# 云台的配置文件
yaw:
  min: -90.0 # 偏航角的最小值
  max: 90.0 # 偏航角的最大值
pitch:
  min: -135.0 # 俯仰角最小值
  max: 0.0 # 俯仰角最大值
# 舵机ID定义
servo_id:
  yaw: 0
  pitch: 1
# 机械零点角度
home:
  yaw: 0.0
  pitch: -90.0
# 样本采集的关节角度
sample_joint_angle:
  yaw:
  - -90.0 # 偏航角的1号标定点
  - 90.0  # 偏航角的2号标定点
  pitch:
  - -90.0 # 俯仰角的1号标定点
  - 0.0   # 俯仰角的2号标定点
# 样本采集的舵机角度
sample_servo_angle:
  yaw:
  - 0.0
  - 0.0
  pitch:
  - 0.0
  - 0.0
# 标定系数 关节到舵机角度的线性映射
joint2servo:
  yaw:
    k: 1
    b: 0
  pitch:
    k: 1
    b: 0